---
- name: "Play 1- cgi website configuration"  
  hosts: webservers
  become: yes
  tasks:
    - name: "loop test"
      yum:
        name: "{{ item }}"
        state: present
      with_items:
      - httpd
      - vim
      - wget
      - tree

